### ISSUE TITLE
How to update Intel Graphics Driver to the latest version?

### ISSUE THREAD

**Issue by ni554n** [Cr0wTom/Mi-Notebook-Pro-Mods#33]
My laptop is currently running the version 25.20.100.6518 from **09-Jan-19**.

I would like to upgrade my Intel Graphics Driver to the latest version or to the modern DCH version, because Chrome sometimes flickers on this version while playing videos.

Tried installing the drivers downloaded from the Intel website, doesn't work. It says OEM should certify the drivers for the device model.

Are you guys running the same version?

**Comment by MarFre22** [comment]
@ni554n , Hi!

I'm using the last intel UHD DCH drivers. To achieve that (sorry some mistake):
- uninstall the OEM drivers with [DDU](https://www.guru3d.com/files-details/display-driver-uninstaller-download.html);
- install the latest DCH intel 620 UHD drivers from intel website;
- use Intel driver updater to regularly update them.

Try it and give some feedback ;)

**Comment by ni554n** [comment]
Thanks for the tips. I have successfully updated to latest DCH driver.

In case anyone wants to know the process:

1. Download the latest DCH Driver from Intel website.
2. **Disconnect from Wi-Fi**. (Important)
3. Uninstall _Intel Graphics Driver_ from Settings > Apps.
4. Install the downloaded DCH driver and Restart.
5. Connect to the internet and _Intel Graphics Command Center_ will be downloaded from Windows Store shortly after.

**Comment by MarFre22** [comment]
@ni554n 
I'm glad you made it :D

But I think using DDU it's very important because it's a powerful tool to clean up all the "garbage" from previous OEM driver - just to make it safe. And thanks for give some feedback, I forgot some steps.

To make it better I think we can merge the two process:

How update the Intel UHD 620 GPU Drivers from OEM to latest official Intel DCH ones? (I think it can be applied to other Intel GPU)
1. Download the latest 620 UHD DCH Driver from Intel website
2. Download DDU tool [here](https://www.guru3d.com/files-details/display-driver-uninstaller-download.html)
3. Disconnect from Wi-Fi. (Important! only connect on step 8 - because windows automatically replaces the driver...)
4. Uninstall the Intel OEM drivers with DDU tool (step 2)
5. Restart
6. Install Intel DCH Drivers you downloaded (step 1)
7. Restart
8. Connect to the internet. Intel Graphics Command Center will be downloaded from Windows/Microsoft store shortly after, if not, open the Windows/Microsoft Store and confirm that.
9. Done :)

@Cr0wTom , can I ask you if it is possible to add me to the repository? because I'd like to write some info to it and also, if possible, create a wiki with summarized issues. 
Thanks :)
